**#This is our first notebook**

*   Here we will learn to write some rudimentary python code and R code, in a notebook style setup, executing the same on a REMOTE Virtual Machine

In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [2]:
# Read the CSV file iris.csv
import pandas as pd
df = pd.read_csv ("/content/gdrive/MyDrive/PGSS2022/L1--6-28-2022/iris.csv", header=None)
df.columns = ['Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width', 'Class']
df

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width           Class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Sepal.Length  150 non-null    float64
 1   Sepal.Width   150 non-null    float64
 2   Petal.Length  150 non-null    float64
 3   Petal.Width   150 non-null    float64
 4   Class         150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [4]:
! pwd

/content

In [5]:
! top

=top - 19:32:22 up 5 min,  0 users,  load average: 0.35, 0.30, 0.17
Tasks:  19 total,   1 running,  17 sleeping,   0 stopped,   1 zombie
%Cpu(s):  6.8 us,  3.3 sy,  0.0 ni, 88.1 id,  1.6 wa,  0.0 hi,  0.1 si,  0.0 st
KiB Mem : 13298580 total, 10122360 free,   945636 used,  2230584 buff/cache
KiB Swap:        0 total,        0 free,        0 used. 12151136 avail Mem

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
      1 root      20   0     992      4      0 S   0.0  0.0   0:00.47 docker-i+
      9 root      20   0  339812  49544  32376 S   0.0  0.4   0:00.61 node
     20 root      20   0   35892   4856   3764 S   0.0  0.0   0:00.48 tail
     32 root      20   0       0      0      0 Z   0.0  0.0   0:04.28 python3
     33 root      20   0  155880  41132  12768 S   0.0  0.3   0:00.38 colab-fi+
     58 root      20   0  199296  59472  14996 S   0.0  0.4   0:01.16 jupyter-+
     59 root      20   0  715340   8436   4612 S   0.0  0.1   0:00.04 dap_mult+
     76 root      20   0  579768 138140  46564 S   0.0  1.0   0:02.11 python3
     96 root      20   0  127440  15860   6252 S   0.0  0.1   0:00.10 python3
    113 root      20   0  714584 341620  32228 S   0.0  2.6   0:14.24 node
    145 root      20   0   18380   1556   1256 S   0.0  0.0   0:00.00 bash
    146 root      20   0 2194000  23732  19184 S   0.0  0.2   0:00.03 drive
    147 root      20   0   11464   1020    924 S   0.0  0.0   0:00.00 grep
    209 root      20   0 2671236  48464  34508 S   0.0  0.4   0:00.14 drive
    285 root      20   0   18380   3004   2760 S   0.0  0.0   0:00.00 bash
    286 root      20   0  712048   2900   2160 S   0.0  0.0   0:00.00 director+
    287 root      20   0    4572    816    752 S   0.0  0.0   0:00.00 tail      >

In [6]:
! nvidia-smi

Tue Jun 28 19:32:37 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   45C    P8    10W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+